// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';

import "./globals.css";

import { ModalCloseProvider, useModalClose } from "./components/close-button-provider";
import NavigationBar from './components/navigation';
import { BottomModalCloseProvider } from './context/firstApproachModalContext';
import { DeviceDetectContextProvider } from './context/deviceDetectContext';
import Footer from './components/Home/footer/footer';
const inter = Inter({
  subsets: ['latin'], // Specify the character sets you need
  variable: '--font-inter', // Optional: Define a CSS variable for easy access
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Midway Securities LTD.",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <ModalCloseProvider>
        <BottomModalCloseProvider>
          <DeviceDetectContextProvider>
            <body
              className={`${inter.className} antialiased`}
            >
              <NavigationBar />
              {children}
              <div className="section-gap px-2 bg-white py-1 font-bold">
                <Footer />
              </div>
            </body>
          </DeviceDetectContextProvider>
        </BottomModalCloseProvider>
      </ModalCloseProvider>
    </html>
  );
}
